## 服务器端口号
server:
  port: 8080
 
## 关于数据库参数的相关配置
spring:
    thymeleaf:
       mode: LEGACYHTML5 
       prefix: /WEB-INF/admin/
       suffix: .html
       encoding: utf-8
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://47.93.30.182:3306/test-dgjs-001?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000
          username: root
          password: 622826mysql
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    redis:
       host: 121.42.143.166
       port: 6379
       timeout: 20000
       ##cluster:
         ##  nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
       ##   maxRedirects: 6
       jedis:
           pool:
               max-active: 8
               min-idle: 0
               max-idle: 8
               max-wait: -1

## MyBatis的相关配置
mybatis:
  # 映射文件位置
  mapper-locations: classpath:mappers/*/*.xml
  # 别名扫描包
  type-aliases-package: com.joyance.springsecurity.persistence
  # 输出SQL执行语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
##日志
logging:
  config: classpath:logback-spring.xml
